apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-volume
  labels:
    app.kubernetes.io/name: source
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: source
  template:
    metadata:
      labels:
        app.kubernetes.io/name: source
    spec:
      containers:
        - name: con1
          image: nginx:latest
          imagePullPolicy: Always
          command: ["echo","Welcome to con1"]
          ports:
            - containerPort: 87
          volumeMounts:
            - name: source
              mountPath: /etc/config
      volumes:
        - name: source
          configMap:
            name: secret
            


