apiVersion: apps/v1
kind: Job
metadata:
  name: switch
spec:
  template:
    spec:
      containers:
        - name: k2
          image: nginx:latest
          imagePullPolicy: Always
          command: ["echo","Job sector"]
      restartPolicy: never
  backoffLimit: 4   
