apiVersion: v1
kind: PersistentVolume
metadata:
  name: files 
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeclaimPolicy: Retain
  hostPath:
    path: /opt/desk
