apiVersion: v1 
kind: Secret
metadata: 
  name: Authenticate
type: Opaque
data:
  userName: S2FiaWxhbjEyMw==
  password: UGFzczEyMyE=

---
apiVersion: v1
kind: Pod 
metadata:
  name: Torun
spec:
  containers:
    - name: Head
      image: cloud:4.7
      imagePullPolicy: Always
      ports:
        - containerPort: 89
      command: ["echo","cloud container launched"]
      volumeMount:
        - name: secret-vol
          mountPath: /etc/secret
  volume:
    - name: secret-vol
      secret:
        secretName: Authenticate


